config/routes.rb
# -*- encoding : utf-8 -*-
Officelunch::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "devise_custom/registrations", :omniauth_callbacks => "users/omniauth_callbacks"}

  resources :dashboard, only: :index do
    get :completion_order, on: :collection
    put :closed_orders, on: :collection
  end
  resources :course_categories
  resources :courses
  resources :menus do
    post :send_email_about_dinner, on: :member
  end
  resources :users, except: [:show, :new, :create]
  resources :orders

  match "users/auth/google_oauth2/callback" => "users/omniauth_callbacks#goole_oauth2", via: :get

  root :to => "dashboard#index"

end

app/controllers/dashboard_controller.rb
# -*- encoding : utf-8 -*-
class DashboardController < ApplicationController

  prepend_before_filter

  def index
    @date = DateTime.now
    @today_menu = Menu.today
    @order = current_user.today_order || current_user.orders.build
    @courses = @today_menu.try(:courses)
  end

  def completion_order
    if Order.today.empty?
      redirect_to dashboard_index_path, notice: I18n.t('front.not_access_to_page')
    end
    new_order_service = CompletionOrderService.new
    @params = new_order_service.get_order_params
  end

  def closed_orders
    Order.today.update_all(closed: true)
    redirect_to dashboard_index_path, notice: I18n.t('front.dashboard.order_close')
  end

end

app/helpers/dashboard_helper.rb
# -*- encoding : utf-8 -*-
module DashboardHelper
  def check_for_active(controller, name)
    "active" if controller.controller_name == name
  end

  def params_for_order_form(order)
    if order.new_record?
      {method: :post, url: orders_path}
    else
      {method: :put, url: order_path(order)}
    end
  end

  def courses_include_to_order(order, c)
    order.courses.include?(c)
  end

  def number_users_to_order_lunch
    Order.where(date_order: Date.today).count
  end

  def dashboard_order_header(order, controller)
    if order.closed && order.not_order
      t("front.dashboard.you_not_order")
    else
      t("front.dashboard.#{@order.closed ? 'you_order' : 'dinner_menu'}")
    end
  end
  
  def today_orders_already_closed
    Order.today.try(:first).try(:closed)
  end
end

app/views/dashboard/_order.slim
= simple_form_for @order, params_for_order_form(@order) do |f|
  - unless @order.closed && @order.not_order
    table class='table table-stripped table-condensed'
      thead
        tr
          th
          th
          th
          th
      tbody
        - (@order.closed ? @order : @today_menu).courses.each do |c|
          tr
            td
              i = c.category.name
            td = c.name
            td
              - unless @order.closed
                input.corse_check_box*{type: "checkbox", price: c.price, name: "order[course_ids][]", value: "#{c.id}", checked: courses_include_to_order(@order, c)}
            td.price = c.price
  
        tr
          td[colspan=3]
            span.font_h4= "#{t('front.orders.sum')}: "
          td
            span.sum.font_h4 = @order.sum
  
    = f.input :user_id, as: :hidden, input_html: {value: current_user.id}
    = f.input :date_order, as: :hidden, input_html: {value: Date.today}
    = f.input :sum, as: :hidden, input_html: {value: @order.sum}
    - unless @order.closed
      = f.input :not_order, as: :boolean
      = f.submit t("save"), class: "btn"

app/views/dashboard/completion_order.slim
.span6.users_order_span
  p
    h3 = t('front.dashboard.order')
  - @params[:user].each do |name, order|
    div*{class: ("user_order_name" if @params[:user].keys.first != name)}
      span = name
      - unless order.closed
        = link_to t('edit'), edit_order_path(order), class: "btn btn-success"
      - if order.not_order
        br
        h3= t('front.dashboard.not_order')
      - else
        table class='table table-stripped table-condensed'
            thead
              tr
                th
                th
                th
            tbody
              - order.courses.each do |c|
                tr
                  td
                    i = c.category.name
                  td = c.name
                  td = c.price

              tr
                td[colspan=2]= "#{t('front.orders.sum')}: "
                td
                  span.sum = order.sum

.span5
  p
    h3 = t('front.dashboard.finish_order')
    table class='table table-stripped table-condensed'
      thead
        tr
          th = t('front.dashboard.courses_name')
          th = t('count')
          th = t('front.orders.sum')
      tbody
        - @params[:need_order].each do |name, count|
          tr
            td = name
            td = count
            td = @params[:total_courses_sum][name]
        tr
          td[colspan=2]= "#{t('front.orders.sum')}: "
          td
            span.sum = @params[:total_sum]

    h4 Кристина (050)226-90-44
    - unless today_orders_already_closed 
      = link_to t('front.dashboard.order_close'), closed_orders_dashboard_index_path, method: :put, class: "btn btn-primary"


= link_to t('back'), dashboard_index_path, class: 'btn'

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/dashboard/index.html.slim
.span6
  p
    h3 #{'Сегодня ' + date_with_weekday(@date) }
  p
    - if @today_menu
      - if @order.closed
        h3.red_font = t('front.dashboard.order_close')
      - else
        =' "С обедом определились #{number_users_to_order_lunch} из #{User.count} пользователей"
      - if Order.all_user_ordered_dinner?
        = link_to t('front.dashboard.to_orders'), completion_order_dashboard_index_path, class: 'btn btn-success'
      h4 = dashboard_order_header(@order, controller)
      = render partial: "order"
    - else
      = link_to "Создать меню на сегодня", new_menu_path, class: "btn"

.span5
  = image_tag "/assets/bonjour.png"