config/routes.rb
# -*- encoding : utf-8 -*-
Officelunch::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "devise_custom/registrations", :omniauth_callbacks => "users/omniauth_callbacks"}

  resources :dashboard, only: :index do
    get :completion_order, on: :collection
    put :closed_orders, on: :collection
  end
  resources :course_categories
  resources :courses
  resources :menus do
    post :send_email_about_dinner, on: :member
  end
  resources :users, except: [:show, :new, :create]
  resources :orders

  match "users/auth/google_oauth2/callback" => "users/omniauth_callbacks#goole_oauth2", via: :get

  root :to => "dashboard#index"

end

app/models/menu.rb
# -*- encoding : utf-8 -*-
class Menu < ActiveRecord::Base
  has_and_belongs_to_many  :courses
  accepts_nested_attributes_for :courses, :reject_if => proc {|attrs| attrs['course_ids'].empty? }

  validates :date_init, presence: true
  validates :date_init, uniqueness: true
  validate :must_have_courses

  before_destroy { courses.clear }


  def self.today
    where(date_init: Date.today).first
  end

   def must_have_courses
    errors.add(:courses_errors, 'Выберите хотя бы одно блюдо') if courses_empty?
   end

   def courses_empty?
     courses.empty?
   end
end
# == Schema Information
#
# Table name: menus
#
#  id         :integer         not null, primary key
#  date_init  :date
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/menus_controller.rb
# -*- encoding : utf-8 -*-
class MenusController < ApplicationController
  before_filter :get_menu, only: [:show, :edit, :update, :destroy]

  def index
    @menus = Menu.order('date_init DESC')
  end

  def show
    @courses = @menu.courses
  end

  def new
    @menu = Menu.new({date_init: Date.today.strftime("%d-%m-%Y")})
  end

  def create
    @menu = Menu.new(menu_params)
    if @menu.save
      redirect_to menus_path, notice: "Меню успешно создано"
    else
      render action: :new
    end
  end

  def edit
  end

  def update
    if @menu.update_attributes(menu_params)
      redirect_to menus_path, notice: "Меню успешно обновлено"
    else
      render action: :edit
    end
  end

  def destroy
    if @menu.destroy
      notice = 'Меню успешно удалено'
    else
      notice = 'Меню не была удалено'
    end
    redirect_to menus_path, notice: notice
  end

  def send_email_about_dinner
    email_digest = DeliverNotificationAboutDinnerService.new(params[:id])
    email_digest.send_email_and_create_google_event
    redirect_to menus_path, notice: I18n.t('front.menus.digest_was_launched')
  end

  private

  def get_menu
    @menu = Menu.find(params[:id])
  end

  def menu_params
    params.require(:menu).permit!
  end

end

app/views/menus/_form.html.slim
= simple_form_for @menu, html: { class: 'form-horizontal' } do |f|

    = f.input :date_init, as: :string,  input_html: {class: 'datepicker'}
    br
    = f.error :courses_errors, class: "error"
    = f.association :courses, as: :check_boxes, required: true

    div class="form-actions"
      = f.submit 'Сохранить', class: 'btn btn-primary'
      | &nbsp;&nbsp;
      = link_to 'Отменить', menus_path, class: 'btn'

app/views/menus/edit.html.slim
h3 Редактирование меню

= render partial: "form"

app/views/menus/index.html.slim
h2 Меню

= link_to "Создать меню", new_menu_path, class: 'btn btn-success'
br
br
table class='table table-stripped table-condensed'
  thead
    tr
      th Дата
      th = t('front.menus.sent?')
      th
      th
  tbody
    - @menus.each do |m|
      tr
        td = link_to m.date_init, menu_path(m), title: "Просмотреть"
        td = m.sent? ? '✓' : ''
        td = link_to t('front.menus.send_emails'), send_email_about_dinner_menu_path(m), class: "btn btn-primary", title: t('front.menus.send_emails_title'), data: {confirm: t('front.menus.realy_send?')}, method: "post"
        td
          = link_to 'Редактировать', edit_menu_path(m), class: 'btn', title: 'Редактировать'
          | &nbsp;&nbsp;
          = link_to 'Удалить', menu_path(m), class: 'btn btn-danger', method: 'delete', title: 'Удалить', data: {confirm: 'Действительно удалить?'}, "data-no-turbolink" => true

app/views/menus/new.html.slim
h3 Новое меню

= render partial: "form"

app/views/menus/show.html.slim
h3 Меню на #{date_with_weekday(@menu.date_init)}

= render partial: "courses/courses"

= link_to "Редактировать", edit_menu_path(@menu), class: "btn"