config/routes.rb
# -*- encoding : utf-8 -*-
Officelunch::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "devise_custom/registrations", :omniauth_callbacks => "users/omniauth_callbacks"}

  resources :dashboard, only: :index do
    get :completion_order, on: :collection
    put :closed_orders, on: :collection
  end
  resources :course_categories
  resources :courses
  resources :menus do
    post :send_email_about_dinner, on: :member
  end
  resources :users, except: [:show, :new, :create]
  resources :orders

  match "users/auth/google_oauth2/callback" => "users/omniauth_callbacks#goole_oauth2", via: :get

  root :to => "dashboard#index"

end

app/models/course_category.rb
# -*- encoding : utf-8 -*-
class CourseCategory < ActiveRecord::Base
  has_many :courses, dependent: :destroy

  validates :name, presence: true
end
# == Schema Information
#
# Table name: course_categories
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/course_categories_controller.rb
# -*- encoding : utf-8 -*-
class CourseCategoriesController < ApplicationController

  before_filter :get_category, only: [:edit, :update, :destroy]

  def index
    @categories = CourseCategory.all
  end

  def new
    @category = CourseCategory.new()
  end

  def create
    @category = CourseCategory.new(category_params)
    if @category.save
      redirect_to course_categories_path, notice: "Категория успешно созадна"
    else
      render action: :new
    end
  end

  def edit
  end

  def update
    if @category.update_attributes(category_params)
      redirect_to course_categories_path, notice: "Категория успешно обновлена"
    else
      render action: :edit
    end
  end

  def destroy
    if @category.destroy
      notice = 'Категория успешно удалена'
    else
      notice = 'Категория не была удалена'
    end
    redirect_to course_categories_path, notice: notice
  end
  
  private

  def get_category
    @category = CourseCategory.find(params[:id])
  end

  def category_params
    params.require(:course_category).permit!
  end

end

app/views/course_categories/_form.html.slim
= simple_form_for @category, html: { class: 'form-horizontal' } do |f|

    = f.input :name

    div class="form-actions"
      = f.submit 'Сохранить', class: 'btn btn-primary'
      | &nbsp;&nbsp;
      = link_to 'Отменить', course_categories_path, class: 'btn'

app/views/course_categories/edit.html.slim
h2 Редактирование категории блюд

= render partial: "form"

app/views/course_categories/index.html.slim
h2 Категории блюд

= link_to "Добавить категорию", new_course_category_path, class: 'btn btn-success'
br
br
table class='table table-stripped table-condensed'
  thead
    tr
      th Название
      th
  tbody
    - @categories.each do |c|
      tr
        td = c.name
        td
          = link_to 'Редактировать', edit_course_category_path(c), class: 'btn', title: 'Редактировать'
          | &nbsp;&nbsp;
          = link_to 'Удалить', course_category_path(c), class: 'btn btn-danger', method: 'delete', title: 'Удалить', confirm: 'Действительно удалить?'

app/views/course_categories/new.html.slim
h2 Новая категория блюд

= render partial: "form"