config/routes.rb
# -*- encoding : utf-8 -*-
Officelunch::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "devise_custom/registrations", :omniauth_callbacks => "users/omniauth_callbacks"}

  resources :dashboard, only: :index do
    get :completion_order, on: :collection
    put :closed_orders, on: :collection
  end
  resources :course_categories
  resources :courses
  resources :menus do
    post :send_email_about_dinner, on: :member
  end
  resources :users, except: [:show, :new, :create]
  resources :orders

  match "users/auth/google_oauth2/callback" => "users/omniauth_callbacks#goole_oauth2", via: :get

  root :to => "dashboard#index"

end

app/views/shared/_top_navigation.html.slim
.navbar.navbar-fixed-top
  .navbar-inner
    .container

      = link_to 'Office lunch', root_path, class: "brand"
      - if current_user
        ul.nav
          li[class=(check_for_active(controller, 'course_categories'))] = link_to "Категории", course_categories_path
          li{class=(check_for_active(controller, 'courses'))} = link_to "Блюда", courses_path
          li{class=(check_for_active(controller, 'menus'))} = link_to "Меню", menus_path
          li{class=(check_for_active(controller, 'users'))}= link_to "Пользователи", users_path

      ul.nav.pull-right.user-info
        - if current_user
          li.dropdown
            a.dropdown-toggle[data-toggle="dropdown" href="#"]
              ' Bonjour,
              b = current_user.name_or_dummy
            ul.dropdown-menu
              li= link_to t('front.header.user_block.edit_profile'), edit_user_registration_path
              li= link_to t('front.header.user_block.exit'), destroy_user_session_path, method: "delete"
        - else
          li= link_to 'Log in', new_user_session_path